name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build user-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest ./user-service

      - name: Push user-service Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

      - name: Save user-service Docker image as artifact
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest -o user-service-image.tar
      - name: Upload user-service Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-service-image
          path: user-service-image.tar

  wallet-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build wallet-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wallet-service:latest ./wallet-service

      - name: Push wallet-service Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wallet-service:latest

      - name: Save wallet-service Docker image as artifact
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/wallet-service:latest -o wallet-service-image.tar
      - name: Upload wallet-service Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: wallet-service-image
          path: wallet-service-image.tar

